language:
  ruby

rvm:
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'
  - '2.6'

matrix:
  fast_finish: true

notifications:
  email: false

install: true

before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v '~> 1.3'

script:
  - gem build numo-narray.gemspec
  - gem install numo-narray-*.gem
  - bundle install
  - rake test
