language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'

matrix:
  fast_finish:
    true

notifications:
  email: false

install: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby gcc ruby-dev rake make -y

script:
  - gem build numo-narray.gemspec
  - gem install numo-narray-*.gem
  - bundle install
  - rake test
