sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull debian
- docker ps -a
- docker run debian /bin/sh -c "apt-get update; apt-get install ruby gcc ruby-dev rake make -y"

script:
  - gem build numo-narray.gemspec
  - gem install numo-narray-0.9.0.2.gem

